WIP: Add faucet bot filter
PlasmNetwork/astar-faucet-bot pull request #13
Opened 2021-11-08 08:25 UTC by y-shijo

2021-11-08 11:52 UTC, hoonsubin requested changes

2021-11-08 11:52 UTC, hoonsubin commented on src/clients/index.ts
> +export * from './requestFilter';
The name `requestFilter`  doesn't look like it should be in the `clients/` folder. What about changing this to something else, or moving the folder and treating it as a database client.

2021-11-08 11:52 UTC, hoonsubin commented on src/clients/requestFilter.ts
> +const redis = new Redis(process.env.REDIS_URL);
Please update the `README.md` file and add the environment variable `REDIS_URL`. Also, please add a quick guide on how to get this value.

2021-11-08 11:52 UTC, hoonsubin commented on src/clients/requestFilter.ts
> +    const untilNextRequest = lastRequestAt + anHourInMilliSecond - now;
I cannot see how long the `untilNextRequest` is supposed to be. I suggest creating a constant that defines how long the cooldown is.
For example:
```ts
// must wait 30 minutes before the next request
const cooldown = 30 * 60 * 1000
```

2021-11-09 10:58 UTC, y-shijo commented
@hoonsubin Please review again :)

2021-11-09 11:05 UTC, hoonsubin requested changes

2021-11-09 11:05 UTC, hoonsubin commented on src/middlewares/requestFilter.ts
> +        const untilNextRequestSec = Math.floor( (untilNextRequest / 1000) - (untilNextRequestMin * 60) );
Please fix the styles. I think everything else looks good!

2021-11-09 11:11 UTC, y-shijo commented
@hoonsubin thank you for your comment. I quickly fixed it, so review it again please 👍

2021-11-09 11:47 UTC, hoonsubin commented
@y-shijo the linter and formatter seem to be strange. I'll format the code

2021-11-09 11:51 UTC, hoonsubin approved these changes
LGTM

2021-11-09 11:51 UTC, merged